name: checkfile-exists

on:
  push:
    branches:
      - master

jobs:
  check-msi-file:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if MSI file exists
      run: |
        if exist "ScientificCalculatorRelease\ScientificCalculatorSetup.msi" (
          echo "MSI file exists"
        ) else (
          echo "MSI file does not exist"
          exit 1
        )
